### ISSUE TITLE
consider support of csi snapshots

### ISSUE THREAD

**Issue by majst01** [metal-stack/csi-driver-lvm#27]
Since k8s v1.17.x csi snapshots are available and they will become GA in 1.20.x. 
https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-cis-volume-snapshot-beta/

Our LVM based approach enables us to support this by leveraging the lvm snapshot functionality.

**Comment by mwennrich** [comment]
The use case for snapshots is, to create a pvc from an existing snapshot via `dataSource`. Example:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-pvc
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: new-snapshot-test
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
```

But for local volumes we have to use `volumeBindingMode: WaitForFirstConsumer`, so this doesn't work, if the scheduler schedules the first consumer pod to another worker node, since on the this worker node that snapshot isn't available. There are no "local snapshots" in k8s ...
