### ISSUE TITLE
helm install  CSIDriver.spec validation error

### ISSUE THREAD

**Issue by lazywhite** [metal-stack/csi-driver-lvm#51]
```
# helm install mytest helm/csi-driver-lvm --set lvm.devicePattern='/dev/loop[0-9]'
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(CSIDriver.spec): unknown field "volumeLifecycleModes" in io.k8s.api.storage.v1beta1.CSIDriverSpec
```

```
 # kc version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by majst01** [comment]
We have not tested csi-driver-lvm on kubernetes < 1.16 tbh

**Comment by lazywhite** [comment]
> We have not tested csi-driver-lvm on kubernetes < 1.16 tbh

do you have a plan to support older versions?

**Comment by majst01** [comment]
> > We have not tested csi-driver-lvm on kubernetes < 1.16 tbh
> 
> do you have a plan to support older versions?

No, because k8s is supported only for the last 3 versions, which is actually 1.19 - 1.21

**Comment by lazywhite** [comment]
> > > We have not tested csi-driver-lvm on kubernetes < 1.16 tbh
> > 
> > 
> > do you have a plan to support older versions?
> 
> No, because k8s is supported only for the last 3 versions, which is actually 1.19 - 1.21

while.. I made some change and it worked now

```
1. modify templates/csi-lvm-driverinfo.yaml
apiVersion: storage.k8s.io/v1beta1    
kind: CSIDriver    
metadata:    
  name: {{ .Values.lvm.driverName }}    
  labels:    
    heritage: {{ .Release.Service }}    
    release: {{ .Release.Name }}    
spec:    
  # Supports persistent and ephemeral inline volumes.    
  #volumeLifecycleModes:       **## comment this field**
  #- Persistent    
  #- Ephemeral    
  # To determine at runtime which mode a volume uses, pod info and its    
  # "csi.storage.k8s.io/ephemeral" entry are needed.    
  podInfoOnMount: true 


2. I'm using minikube, so should enable PodSecurityPolicy
minikube addons enable pod-security-policy
```
